# Generated by Django 5.0.6 on 2024-06-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Не указано'), (2, 'Мужчина'), (3, 'Женщина')])),
                ('photo', models.FileField(upload_to='main_photos/')),
                ('majority', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyPersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField()),
                ('quote', models.TextField()),
                ('financial_state', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.myperson')),
            ],
        ),
    ]
