# Generated by Django 5.0.6 on 2024-06-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myperson',
            options={'verbose_name': 'Краткая инфа о человеке', 'verbose_name_plural': 'Краткая инфа о людях'},
        ),
        migrations.AlterModelOptions(
            name='mypersondetail',
            options={'verbose_name': 'Подробная инфа о человеке', 'verbose_name_plural': 'Подробная инфа о людях'},
        ),
        migrations.AlterField(
            model_name='myperson',
            name='photo',
            field=models.FileField(upload_to='media/main_photos'),
        ),
    ]
