# Generated by Django 5.0.6 on 2024-06-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_myperson_options_alter_mypersondetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('why_you', models.TextField()),
            ],
            options={
                'verbose_name': 'Заявка на редактора',
                'verbose_name_plural': 'Заявки на редактора',
            },
        ),
    ]
