# Generated by Django 5.0.6 on 2024-06-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_groups_remove_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
